In [1]:
import numpy as np

In [2]:
[1,2,3]  #[ defines no. of dimension

[1, 2, 3]

In [3]:
np.random.randint(1,100,(2,3,4)) #2d = two deimension array
#2 = number of blocks within array
#3 = number of rows within the block
#4 = number of columns within the rows

array([[[62, 71, 90, 45],
        [56, 37, 21, 23],
        [27, 76, 61, 61]],

       [[29, 44, 49, 68],
        [69, 35, 62, 75],
        [73, 16, 68, 42]]], dtype=int32)

## Understanding Dimensions of Array:

In [4]:
#1D Array:

ary1d = np.array([1,2,3])

print("Shape of Array",ary1d.shape)
print("Dimensions",ary1d.ndim)
print("Size",ary1d.size)

Shape of Array (3,)
Dimensions 1
Size 3


In [5]:
ary2d = np.array(
    [
        [1,2,3],
        [4,5,6]
    ]
)

print("Shape of Array",ary2d.shape)
print("Dimensions",ary2d.ndim)
print("Size",ary2d.size)

Shape of Array (2, 3)
Dimensions 2
Size 6


In [6]:
ary3d = np.array(
    [
        [
            [1,2,3,4,5],
            [6,7,8,9,10],
            [11,12,13,14,15]
    
        ]
    ]
)

print("Shape of Array",ary3d.shape)
print("Dimensions",ary3d.ndim)
print("Size",ary3d.size)

Shape of Array (1, 3, 5)
Dimensions 3
Size 15


In [7]:
ary4d = np.array(
    [
        [
            [
                [1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15],
                [16,17,18,19,20]

            ]
        ]
    ]
)

print("Shape of Array",ary4d.shape)
print("Dimensions",ary4d.ndim)
print("Size",ary4d.size)

Shape of Array (1, 1, 4, 5)
Dimensions 4
Size 20


In [8]:
ary4d = np.array([[[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]]]])

print("Shape of Array",ary4d.shape)
print("Dimensions",ary4d.ndim)
print("Size",ary4d.size)

Shape of Array (1, 1, 4, 5)
Dimensions 4
Size 20


In [9]:
ary4d

array([[[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]]]])

In [10]:
ary4d.reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [11]:
ar2=(ary4d.size//2)
#ar3=ar2.astype('int')
ary4d.reshape((ary4d.ndim)//2,ar2)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [12]:
print(ary4d.size/2)
type(ary4d.size/2)

10.0


float

In [13]:
ary4d.ndim

4

In [14]:
ary4d.size

20

## Transpose Array

In [15]:
ary3d

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]])

In [16]:
ary3d.T

array([[[ 1],
        [ 6],
        [11]],

       [[ 2],
        [ 7],
        [12]],

       [[ 3],
        [ 8],
        [13]],

       [[ 4],
        [ 9],
        [14]],

       [[ 5],
        [10],
        [15]]])

In [17]:
ary3d.ndim

3

In [18]:
ary3d.shape

(1, 3, 5)

In [19]:
ary3d.size

15

In [20]:
ary4d

array([[[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]]]])

In [21]:
ar7=ary4d.T

In [22]:
ary4d.shape

(1, 1, 4, 5)

In [23]:
ar7.shape

(5, 4, 1, 1)

In [24]:
ar1d=np.array([10,20,30])

print("Shape of Array",ar1d.shape)
print("Dimensions",ar1d.ndim)
print("Size",ar1d.size)

Shape of Array (3,)
Dimensions 1
Size 3


In [25]:
ar1d

array([10, 20, 30])

In [29]:
ar1d.T

array([10, 20, 30])

In [31]:
ar2d=np.array([[40,50,60],[70,80,90]])

print("Shape of Array",ar2d.shape)
print("Dimensions",ar2d.ndim)
print("Size",ar2d.size)

Shape of Array (2, 3)
Dimensions 2
Size 6


In [32]:
ar2d

array([[40, 50, 60],
       [70, 80, 90]])

In [33]:
ar2d.T

array([[40, 70],
       [50, 80],
       [60, 90]])

In [35]:
ar3d=np.array(
    [
        [
            [40,50,60],
            [70,80,90],
            [100,110,120]    
        ]
    ]
)

print("Shape of Array",ar3d.shape)
print("Dimensions",ar3d.ndim)
print("Size",ar3d.size)

Shape of Array (1, 3, 3)
Dimensions 3
Size 9


In [36]:
ar3d

array([[[ 40,  50,  60],
        [ 70,  80,  90],
        [100, 110, 120]]])

In [37]:
ar3d.T

array([[[ 40],
        [ 70],
        [100]],

       [[ 50],
        [ 80],
        [110]],

       [[ 60],
        [ 90],
        [120]]])

In [39]:
ar4d=np.array(
    [
        [
             [
                [40,50,60],
                [70,80,90],
                [100,110,120],    
                [130,140,150]
             ]
        ]
    ]
)

print("Shape of Array",ar4d.shape)
print("Dimensions",ar4d.ndim)
print("Size",ar4d.size)

Shape of Array (1, 1, 4, 3)
Dimensions 4
Size 12


In [40]:
ar4d

array([[[[ 40,  50,  60],
         [ 70,  80,  90],
         [100, 110, 120],
         [130, 140, 150]]]])

In [41]:
ar4d.T

array([[[[ 40]],

        [[ 70]],

        [[100]],

        [[130]]],


       [[[ 50]],

        [[ 80]],

        [[110]],

        [[140]]],


       [[[ 60]],

        [[ 90]],

        [[120]],

        [[150]]]])

In [46]:
ar5d=np.array(
    [
        [
            [
                 [
                    [40,50,60],
                    [70,80,90],
                    [100,110,120],    
                    [130,140,150],
                    [151,152,153]

                 ]
            ]
        ]            
    ]
)

print("Shape of Array",ar5d.shape)
print("Dimensions",ar5d.ndim)
print("Size",ar5d.size)    

Shape of Array (1, 1, 1, 5, 3)
Dimensions 5
Size 15


In [47]:
ar5d

array([[[[[ 40,  50,  60],
          [ 70,  80,  90],
          [100, 110, 120],
          [130, 140, 150],
          [151, 152, 153]]]]])

In [48]:
ar5d.T

array([[[[[ 40]]],


        [[[ 70]]],


        [[[100]]],


        [[[130]]],


        [[[151]]]],



       [[[[ 50]]],


        [[[ 80]]],


        [[[110]]],


        [[[140]]],


        [[[152]]]],



       [[[[ 60]]],


        [[[ 90]]],


        [[[120]]],


        [[[150]]],


        [[[153]]]]])