# Numpy - Library / Module / Package in Python:

In [1]:
# Numpy is made by c++

#[1,2,3,4,5,6] #Vector

#[[1,2,3],[4,5,6,]] #Two Dimensional Array

py =[1,2,3,4,5]
print(py*2)    #it will print the list 2 times

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [2]:
#!pip install numpy # numpy = Numerical Python

In [3]:
import numpy as np

In [4]:
#creating 1D array
    #An array is a fundamental data structure in computer science that stores a collection of elements, all of the same type, 
    #in contiguous memory locations. This allows for efficient access and manipulation of the elements using indices.

arr1 = np.array([1,2,3,4,5,6])   #always pass list in array to print value.

In [5]:
print(arr1*2)

[ 2  4  6  8 10 12]


In [6]:
#2D array

arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [7]:
arr2.shape

(2, 3)

In [8]:
#Basic Operation on Arrays: Numpy Allows you to perform element-wise operations on arrays.
#These operations are much faster than using regular python Loops or List.

In [9]:
arr3 = np.arange(10,51)   #arange=adds element through range
arr3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [10]:
arr3.shape

(41,)

In [11]:
arr6 = np.random.randint(1,1000,(3,4))   #randint = random integer

In [12]:
print(arr6)   #we can use print(arr6) to obtain results.

[[742 988 358  24]
 [338 510  76 334]
 [667 112 800 794]]


In [13]:
print(arr6.dtype)

int32


In [14]:
print(arr6.shape)

(3, 4)


In [15]:
print(arr6.ndim)

2


In [16]:
print(arr6.size)

12


In [18]:
arr7 = np.array([10,2,3,4,5,78,3])

print(arr7.sum())

sine_values = np.sin(np.radians(arr7))
cosine_values = np.cos(np.radians(arr7))
square_root = np.sqrt(arr7).round(2)   #.round = if you want to restrict decimal
exponential = np.exp(arr7).round(2)

print(sine_values, "\nCosine Value",cosine_values, "\nSquare Root",square_root, "\nExpon",exponential)

105
[0.17364818 0.0348995  0.05233596 0.06975647 0.08715574 0.9781476
 0.05233596] 
Cosine Value [0.98480775 0.99939083 0.99862953 0.99756405 0.9961947  0.20791169
 0.99862953] 
Square Root [3.16 1.41 1.73 2.   2.24 8.83 1.73] 
Expon [2.202647e+04 7.390000e+00 2.009000e+01 5.460000e+01 1.484100e+02
 7.498417e+33 2.009000e+01]


In [19]:
np.random.randint(10,51,(3,4))

array([[12, 37, 10, 17],
       [30, 29, 35, 13],
       [33, 13, 39, 40]], dtype=int32)

In [20]:
arr8 = np.random.randint(10,51,(3,4))
arr8

array([[48, 44, 49, 32],
       [30, 21, 36, 11],
       [47, 13, 32, 25]], dtype=int32)

In [21]:
arr8[0,2] ## Accessing elements from arry arr8 [row number, column] #element row is starting from 0.

np.int32(49)

In [22]:
np.array([x for x in arr8])

array([[48, 44, 49, 32],
       [30, 21, 36, 11],
       [47, 13, 32, 25]], dtype=int32)

In [23]:
slice = arr8[0:1]
slice

array([[48, 44, 49, 32]], dtype=int32)

In [24]:
slice.ndim

2

In [26]:
arr8.ndim

2

In [27]:
np.random.randint(0,100,(1,2,3)) #1 is no. of arrays, #2 is no. of rows, #3 is no. of columns

array([[[13, 15, 71],
        [35, 93, 80]]], dtype=int32)

In [33]:
#1d array of even numbers
np.arange(1,10,2) #for even numbers

array([1, 3, 5, 7, 9])

In [36]:
#1d array of even numbers
np.arange(2,10,2) #for Odd numbers


array([2, 4, 6, 8])